version: '2'
services:
  bottleneck:
    image: ${DEPLOY_IMAGE}
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "0:3000"
    environment:
      - REDIS_HOST=${REDIS_HOST}
    logging:
      driver: awslogs
      options:
        awslogs-group: ${PROJECT_NAME}
        awslogs-region: ${REGION}
        awslogs-stream-prefix: ${PROJECT_NAME}