version: '2'

services:
  express:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    links:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"